Code review
LeandroDCM/AUTH_TEST_API pull request #1
Opened 2022-11-01 22:13 UTC by LeandroDCM

Public Route

- [x] Register user{name,email,password,confirmPassword} UpperCase Number Special Symbol. [Bcrypt]

- [x] Login with username/pass , email/pass

- [x] Recover Email/pass [NodeMailer]

 Private Route [JWT]

- [x] User make post - route
- [x] User update post - route
- [x] User delete post - route

- [x] Admin -> Delete post and Users
- [x] Mod -> delete Posts ( if isn't a admin post)
- [x] Register -> Send email to confirm the registration (account)
- [x] If the user isn't confirmed -> he can't post anything 

```ts
routes.post("/auth/register", UserController.register);

// Login User Route
routes.post("/auth/login", UserController.login);

// Recover User Route
routes.put("/auth/recover", EmailController.recover);

// Reset Password
routes.patch("/auth/reset/:token", UserController.resetPassword);

//Activate Account
routes.post("/auth/activate/:token", UserController.activate);

//Private Route
//function checkToken to check if token is authorized to access private route
routes.get("/user/", checkToken, UserController.userIndex);

// Make/update/delete post route
routes.get("/posts/", checkToken, PostController.index);
routes.get("/posts/:id", checkToken, PostController.userPosts);
routes.post("/user/post", checkToken, PostController.makePost);
routes.patch("/user/:postid", checkToken, PostController.updatePost);
routes.delete("/user/:postid", checkToken, PostController.deletePost);
routes.delete("/user/delete/:id", checkToken, UserController.deleteUser);
```

2022-11-03 14:59 UTC, rafaelcaet requested changes

2022-11-03 14:59 UTC, rafaelcaet commented on src/app.ts
> +const port = process.env.SERVER_PORT;
This should be ```const port = +process.env.SERVER_PORT ```

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/EmailController.ts
> +    })) as UserInterface;
Create a new interface called ```IUser``` in interface folder to typing user's.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +const { User } = require("../models/User");
Try to change require to import

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +    )) as UserInterface;
Create a new interface called IUser in interface folder to type users.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +        }) as PostInterface;
Create a new interface called IPost in interface folder to type posts.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +        throw new Error("Account not activated");
move this ``` throw new Error("Account not activated");``` to catch. The clause catch is responsable to throw the errors.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +    const postid = req.params.postid;
Type this with string

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +    )) as UserInterface;
Create a new interface called IUser in interface folder to type users.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +    const post = (await Post.findById(postid)) as PostInterface;
Create a new interface called IPost in interface folder to type posts.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +    if (post === null || !post)
Redundancy. ```post === null``` is the same thing as ```!post```. Use ```!post```.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +    if (user._id.toString() === post.user.toString()) {
Remove .toString. _id and post.user should be typed on IUser and IPost with string.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +      const postid = req.params.postid;
type as string

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +      )) as UserInterface;
Create a new interface called IUser in interface folder to type users.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +      const thisPost = (await Post.findById(postid)) as PostInterface;
Create a new interface called IPost in interface folder to type posts.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +      if (!thisPost || thisPost === null)
Redundancy. thisPost === null is the same thing as !thisPost. Use !thisPost.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +        user._id.toString() === thisPostPoster._id.toString()
Remove .toString(). _id and thisPostPoster_id should be typed on IUser and IPost with string.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +      );
move this throw new Error("Access denied. You do not have permission to delete this post"); to catch. The clause catch is responsable to throw the errors.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +      const posts = (await Post.find({}, "name post -_id")) as PostInterface;
Create a new interface called IPost in interface folder to type posts.

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +      const id = req.params.id;
type as string

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +      }
The return of idIsValid must be true or false and the validation can be done as follows: 
```ts
if(idIsValid(id))
       return `message`;
```

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +      )) as PostInterface;
- id must be typed as string

- PostInterface must be change to IPost. ✈

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/PostController.ts
> +      if (!posts || posts.length === 0) {
This should be
 ```ts 
if(!post.length){}
```

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/UserController.ts
> +    })) as UserInterface;
Change to IUser 🚀🚀🚀🚀

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/UserController.ts
> +      }) as UserInterface;
Change to IUser 🚀🚀🚀🚀

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/UserController.ts
> +    })) as UserInterface;
Change to IUser 🚀🚀🚀🚀

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/UserController.ts
> +      )) as UserInterface;
Change to IUser 🚀🚀🚀🚀

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/UserController.ts
> +    const { token } = req.params;
type this token. 
```ts
const {token} = req.params as {token: 🛸}
```

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/UserController.ts
> +      )) as [{ role_id: number; username: string }];
This 
```ts 
User.find()
``` 
should be changed to 
```ts
User.findOne()
```

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/UserController.ts
> +      const user = (await User.findById(userId)) as UserInterface;
Use IUser 🚀🚀🚀🚀

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/UserController.ts
> +      })) as UserInterface;
Use IUser 🚲

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/UserController.ts
> +      }
We have to change it

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/UserController.ts
> +      const userInformation = jwt.verify(token, secret) as any;
This should be like 
```ts
const userInformation = jwt.verify(token, secret) as {username: string}
```

2022-11-03 14:59 UTC, rafaelcaet commented on src/controllers/UserController.ts
> +      throw new Error("Something went wrong!");
We have to change it.

2022-11-04 16:03 UTC, rafaelcaet reviewed
@andremury

2022-11-07 13:11 UTC, andremury requested changes
#### Commentary:
General:
Very good, concise code, and very linear reading. Improvements can be made but you'll need a little more knowledge, and context but this comes from practice.

Improvements:
 - You should pay more attention to error codes and error handling because this can lead the comsumer to a misunderstanding of what is happening in the server side.

 - Code could follow [DRY](https://parrot-six.vercel.app/general-programming/solid#2-simpler-things-first-dry) better, to clean the code and make it more reusable

In general, very good  😊👍

2022-11-07 13:11 UTC, andremury commented on src/utils/USER_ROLES.ts
> +export default USER_ROLES;
You can use Enums for this purpose
```ts
export enum Role {
  ADM = 3,
  MOD = 2,
  USER = 1
};

//
const user.role = Role.ADM;
```

2022-11-07 13:11 UTC, andremury commented on src/utils/postIdValidator.ts
> +  }
You can use short assert like

```ts
export default function idIsValid(postId: string) {
   return !(postId && mongoose.Types.ObjectId.isValid(postId));
}
```
Logical operator works just like math, so
`(!a || !b) === !(a && b)`
Because OR is a sum and AND is a multiplication, so

`¬` is inverse, then inverts the nested logical operator (denial)
`¬A + ¬B = ¬(A * B)`
When you "distribute" `¬` among `A`, `*` and `B`, you also "multiply" `*` and deny it, so inverse of `*` is `+`
Then you have 
`¬A ¬* ¬B` => `¬A + ¬B`, `(!a || !b) === !(a && b)`
`¬(A ¬+ B)` => `¬(A * B)`

Take a look on the [Morgan's laws](http://ix.cs.uoregon.edu/~michaelh/111/misc/inverting-logical-exprs.html) when you can

2022-11-07 13:11 UTC, andremury commented on src/controllers/EmailController.ts
> +});
Everything that is not part of the "inside" of the app, should be named as a `Service`, or a `Client`, and should be available to the whole app. So, a mailgun client should be separated as `MailgunClient` or `EmailService` and instantiated in the controller, so this way if you want to use it anywhere else, you won't need to create mg instances every time.

```ts
interface MailgunConfig {
  apiKey: string,
  domain: string
}
class MailgunClient {
  client: Mailgun

  constructor (config: MailgunConfig){
     this.client = mailgun(config);
  }

  send(/*The object with the data*/) {
    //.. method to send
  }
 //... other methods you want
}

const mailgunCli = new MailgunService(/*config obj*/);
export { mailgunCli, MailgunService };
```

Then you import `mailgunCli`
and use like

```ts
import {mailgunCli} from 'util/MailgunClient`;
mailgunCli.send(/*...*/)
```

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +    )) as IUser;
Error from this section won't be caught

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +        return res.json({
missing code 403

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +      return res.json({
error code 403

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +      return res.status(500).json({
400

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +      return res.status(400).json({
wouldn't use 400 for "not found", but 422 or 404. 422 is preferrable

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +      return res.json({ Error: "Cannot update another users post." });
status 403

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +        return res.status(500).json({
400

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +        res.status(404).json({
choose an error code for not found. Either 422 or 404 would work, but use the same code for all the endpoints

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +      return res.status(500).json({
403

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +      return res.status(500).json({
403

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +      }
You can create a helper to avoid this wet code, we do it by something like

```ts
export function canDeletePost(user, post) {
  const postOwner = // find post owner

  // then check the combinations from top to bottom
  if(user.role === Role.ADM) return true;
  if(user.role === Role.MOD && user.id === postOwner.id) return true; 
  // other conditions
  // There are cleaner ways to do it but for study purposes, this works fine

}
```

Then you do like

```ts
if(await canDeletePost(user, post)) {
   await Post.findByIdAndDelete(postid);
     return res.status(200).json({
       msg: "Post deleted successfully",
    });
}
```

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +        return res.status(500).json({
400

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +      res.status(500).send(error);
You should only use 500's if the server break

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +        return res.json({
missing error code

2022-11-07 13:11 UTC, andremury commented on src/controllers/PostController.ts
> +      res.status(500).json({
400

2022-11-07 13:11 UTC, andremury commented on src/controllers/UserController.ts
> +        msg: `Fields: ${errors.join(",")} are required!`,
no need, you can just use the plural even for 1

2022-11-07 13:11 UTC, andremury commented on src/controllers/UserController.ts
> +      return res.status(422).json({ msg: "Invalid password!" });
401 <- Unauthorized
Never specify what's wrong to the user in these cases, you must say
`Invalid username or password`

2022-11-07 13:11 UTC, andremury commented on src/controllers/UserController.ts
> +        return res.json({
error code

2022-11-07 13:11 UTC, andremury commented on src/controllers/UserController.ts
> +      return res.json({
error code 403

2022-11-07 13:11 UTC, andremury commented on src/controllers/UserController.ts
> +        return res.status(500).json({
error 400

2022-11-07 13:11 UTC, andremury commented on src/controllers/UserController.ts
> +      return res.json({
403

2022-11-07 13:11 UTC, andremury commented on src/controllers/UserController.ts
> +      return res.json({
403

2022-11-07 13:11 UTC, andremury commented on src/middleware/checkToken.ts
> +    res.status(400).json({ msg: "Invalid Token" });
403

2022-11-07 19:12 UTC, LeandroDCM commented on src/controllers/PostController.ts
> +    )) as IUser;
I don't understand. Is the (!user) useless? or should it all be inside the trycatch? or maybe something i don't see.

2022-11-07 20:13 UTC, LeandroDCM commented on src/controllers/PostController.ts
> +    )) as IUser;
I assumed it was useless (after some testing and not being able to trigger it) and removed it.

2022-11-08 11:06 UTC, andremury commented on src/controllers/PostController.ts
> +    )) as IUser;
!User is not useless but if findOne throws any exception like "Key username does not exists in scheme User", it'll not be caught. !user will work if you don't find any user, but the mongo function can fail too

2022-11-08 11:07 UTC, andremury commented on src/controllers/PostController.ts
> +    )) as IUser;
You should put it inside de try catch

2022-11-08 11:12 UTC, andremury commented on src/utils/canDeletePost.ts
> +export async function canDeletePost(user: IUser, thisPost: IPost) {
This is the idea. In the future we'll see better ways to do it, but this is the path

2022-11-08 11:19 UTC, andremury approved these changes

2022-11-08 13:45 UTC, merged